### PR TITLE
Support getters/setter inside any metadata (props, methods, deepThings...)

### LINKED ISSUE #125: getter/setter cannot run
i will fix it, now

### PR DESCRIPTION
**Pull request by koresar**
Closes #125 #127 (and few other issues throughout the years).

### CODE REVIEW

**Comment by koresar** [comment]
@FredyC hey, do you want to take a look? :)

Hey, @lornally , it's happening :)

**Comment by koresar** [comment]
This PR will be merged by me in 2-3 days if everyone is fine with it. :)

**Comment by FredyC** [comment]
@koresar Sorry, don't wait for me, my interest in stamps is kinda gone for last year or so. I don't use them anywhere anymore. I just couldn't get over the missing TypeScript support :)

**Comment by koresar** [comment]
I wish I knew how to support TypeScript.

But this project needs someone sane, someone like you to review all my crazy ideas. Can you be that person?

**Comment by FredyC** [comment]
I would love to help, but having stamps in my hands a year ago I don't really know what you are trying to achieve here anymore :)

**Comment by koresar** [comment]
I just want getters and setters to be the first class citizens. Like
functions.

**Comment by FredyC** [comment]
Ok, I said it in a wrong way. Not that I wouldn't understand exactly what you mean here, but it's just hard to imagine any implications coming from it. Even after seeing the PR you just linked, I am like "whaaat? it doesn't make sense to me anymore".

Sorry.

**Comment by lornally** [comment]
i think less is better, maybe less effect is right for a framework, so i support this.  and maybe we can try to support typescript and coffeescript.

**Comment by lornally** [comment]
and I think, the props and methods are sugar only, we need not limit it, we can free use the keys, and we use it more reasonable, just because it is specificate, not because we can't use it more freely.  my English is poor enough, so maybe I can not explain what I mean. sorry:)

**Comment by koresar** [comment]
I think I understand what you mean.
We do not limit "methods" to bytes functions. Anything can go there.

**Comment by lornally** [comment]
yes, that is what i mean, and, I think props is same with methods. so we can build methods in props, but we are not suggest to do that.

**Comment by koresar** [comment]
Correct.

Props are per instance, each copied by reference every time an object is
created.

Whereas methods are per stamp. Objects created from that stamp will have
the "methods" object as its prototype.

**Comment by lornally** [comment]
yes, you are right, that my mistake, props is different  with methods,  so we need make the getter/setter in methods?

**Comment by koresar** [comment]
I believe getters/setters should be no different from regular object properties. Thus all the stamp elements must support them. - props, methods, statics, deepProps, conf, deepConf, etc.

**Pull request merged**
