### PR TITLE
Objects and Prototypes typo on compose.js

### LINKED ISSUE #116: Typo on compose.js comments
Line 72: "bjects" instead of "objects".

### PR DESCRIPTION
**Pull request by jaysoifer**
Closes #116

### CODE REVIEW

**Comment by FredyC** [comment]
Thank you. Appreciated :)

**Comment by jaysoifer** [comment]
Hope to someday be able to send more significant contributions 😄

**Comment by FredyC** [comment]
If you want to contribute, you can have a look at https://github.com/stampit-org/stamp

Stampit itself is kinda deprecated as we made it more into ecosystem of small stamps and there is a already some interesting stuff. You can read more about the change here: https://medium.com/@koresar/episode-14-new-stamp-it-as-a-replacement-of-stampit-191ef0f4c53e

**Comment by jaysoifer** [comment]
@FredyC thank you. This week is a mess but I will look into it 😄

**Pull request merged**
