### PR TITLE
[#32] Priority, configuration, and warnings.

### PR DESCRIPTION
**Pull request by ericelliott**

### CODE REVIEW

**Comment by koresar** [comment]
Gave this a deep thought:
> * Instance properties have lowest priority

This is the biggest change for stampit users.
* The current stampit (v2) assumes that stamp properties are the defaults, and the stamp's argument is the actual state.
* The specs does it vice-versa. Stamp properties are the actual state, an the stamp's argument is the defaults.

I have a mixed feeling about that. I loved the fact that stamp brings some defaults in case the stamp argument does not provide it. The following code implements the **same behavior**. There is no other way to implement it consistently.

stampit v2:
```js
const DbConnection = stampit().refs({ host: "example.com", port: 1234 });
const conn = DbConnection({ host: "localhost" }); // reusing the default port
```

this PR proposal:
```js
const DbConnection = compose({
  inititalizators: [ ({ host, port }, { instance }) => {
    instance.host = host || instance.host; // this is a long line which could be avoided
    instance.port = port || instance.port; // unfortunate almost copy&paste
  } ]
});
const conn = DbConnection({ host: "localhost" });
```

I don't like the fact that now I need to copy&paste the same line for each property I wanna *defaultize*.

Do I miss something?

**Comment by ericelliott** [comment]
RE: first example
```js
const DbConnection = stampit().refs({ host: "example.com", port: 1234 });
const conn = DbConnection({ host: "localhost" }); // reusing the default port
```

Can't you get that behavior like this?

```js
import { init } from 'stampit/utils';

const override = init( (options, { instance }) => {
  Object.assign(instance, options);
});

const DbConnection = stampit().refs({ host: "example.com", port: 1234 }, override);
const conn = DbConnection({ host: "localhost" }); // reusing the default port
```

We could even provide `override` as a Stampit util:

```js
import { init, override } from 'stampit/utils';

const DbConnection = stampit().refs({ host: "example.com", port: 1234 }, override);
const conn = DbConnection({ host: "localhost" }); // reusing the default port
```

**Comment by koresar** [comment]
You have just passed the `override` stamp to the `refs()` method. Please, correct the typo. I'm not sure what you meant.
> `const DbConnection = stampit().refs({ host: "example.com", port: 1234 }, override);`

**Comment by ericelliott** [comment]
Fixed, I think. :)

**Comment by ericelliott** [comment]
Utility-free version:

```js
const DbConnection = compose({ properties: { host: "example.com", port: 1234 }});
const conn = DbConnection.compose({ properties: { host: "localhost" }})(); // reusing the default port
```

**Comment by koresar** [comment]
I gave it more thought. Well, it seems like everything can be solved with the utility functions.

**Comment by koresar** [comment]
> `const conn = DbConnection.compose({ properties: { host: "localhost" }})();`

Is there a way to assign properties without creating any new stamps?

**Comment by koresar** [comment]
Answering my own question. Sure!
```js
const defaults = (defaultProps) => init((options, {instance}) => _.defaults(instance, defaultProps));
```

**Comment by ericelliott** [comment]
Consider this:

```js
// db-connection.js
const DbConnection = compose({ properties: { host: "example.com", port: 1234 }});

export default (options) => {
  return DbConnection.compose({ properties: options})();
};
```

```js
import DbConnection from 'db-connection';

const conn = DbConnection({ host: "localhost" });
```

**Comment by koresar** [comment]
Still, your solution creates one more stamp :)))
```js
const conn = DbConnection({ host: "localhost" }); // <- .compose will be invoked.
```
Whereas my example does not create stamps.

**Comment by koresar** [comment]
We should implement that as an utility stamp:
```js
module.exports = function(defaultProps) {
  return compose({ initializers: [ function(options, {instance}) {
    _.defaults(instance, defaultProps);
  } ] } );
};
```

**Comment by ericelliott** [comment]
:+1:

**Pull request merged**
