### PR TITLE
example.js code simplification

### PR DESCRIPTION
**Pull request by koresar**
Code simplification. Further effort to make it an NPM module. Also better readability. Improved performance. Safer code.

### CODE REVIEW

**Comment by JosephClay** [comment]
I'm good with this. :+1:

> Further effort to make it an NPM module

Not sure I understand what changes make this more of an NPM module.

**Comment by unstoppablecarl** [comment]
Looks great. 

Don't forget #65

**Comment by koresar** [comment]
> Not sure I understand what changes make this more of an NPM module.

Yeah, I should have elaborate on that too. :)

So, the idea is to publish this module to NPM, but also allow others to reuse this new module parts. Namely the `createStamp` and `mergeComposable` functions. By reusing these a user can easily create his own implementation(s) of the `compose` function.

For example, if I wanna track each time a descriptor is merged I'll do that (this in not the final variant):
```js
import {createStamp, mergeComposable} from 'composejs';

function myMergeComposable(dst, src) {
  console.log(`merging ${(src && src.compose) || src} descriptor`; // TRACKING
  return mergeComposable(dst, src);
}

function compose(...composables) {
  return createStamp(composables.reduce(myMergeComposable, myMergeComposable({}, this)), compose);
}
```

**Comment by koresar** [comment]
@unstoppablecarl oh, mate, I'm working on it. Currently I'm just waiting for @ericelliott 's help. There is an idea to use this service https://www.omniref.com/ to annotate the code. However, to integrate it to this github org. I need admin access to the "stampit-org".

**Pull request merged**
