### PR TITLE
fix issue #125, getter/setter will be success

### PR DESCRIPTION
**Pull request by lornally**
fix getter/setter error.

### CODE REVIEW

**Comment by koresar** [comment]
Wow! Looks like a simple fix. Let me check this change more thoroughly.

Before accepting the PR I would need to announce it and ask other people opinions. 

Also, unit tests are lacking. I'll deal with it.

**Comment by lornally** [comment]
but, i can not fix it in stampit, because deep, static...... maybe, that all need rewrite, rewrite all  code for properties clone.

**Comment by lornally** [comment]
i do a new pr, more exact for assign.

**Comment by koresar** [comment]
I have just gave it another thought. 
Please, take a look at this comment: https://github.com/stampit-org/stamp-specification/issues/7#issuecomment-122904939

Turns out the specification already support getters and setters. All we need is to keep them inside the `propertyDescriptors` metadata!

Thus, I believe that `stamp-specification` does not need change. Instead, we just need to improve the `stampit` module.

Sorry for the confusion @lornally . You have gave me the confidence. 👍  Thank you very much for that!!!

**Comment by lornally** [comment]
you are welcome.  cool, we have  propertyDescriptors, and actually, we have it in stampit, do we replace it in stampit?

**Pull request closed without merging**
