### PR TITLE
[WIP] Use Object.assign instead of lodash

### LINKED ISSUE #95: Use smaller assign instead of lodash.assign
Another finding [regarding bundle size](https://github.com/stampit-org/stampit/issues/212).

At first it might seem that `lodash.assign` is winner here with 6.8K minified vs 7.6K for polyfilled `Object.assign`. However there are two main reasons why would I stick to `Object.assign`.

 * It's standardized so eventually need for polyfill may begone (essentially [only IE11, old Safari and Android](https://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign) needs it)
 * It has support for Symbol included thus solving #86 in most cases. If lodash ever adds support for it, I am sure that size will go up much more.

### PR DESCRIPTION
**Pull request by FredyC**
Fixes #95

### CODE REVIEW

**Comment by FredyC** [comment]
Hmm I see this is gonna be problematic for tests as there is no polyfill.

**Comment by ericelliott** [comment]
Which engine is this failing on?

**Comment by FredyC** [comment]
I am clueless on that, Travis is golden compared to this, I don't see any information on what platform it was executing...

**Comment by FredyC** [comment]
Ah I could have scrolled down bit more :) Yea it's failing on 0.10 obviously and it will fail on 0.12 too ... http://node.green/#Object-static-methods

**Comment by koresar** [comment]
Wow! Hold off with this PR please!
I'm running code on production using node 0.10. Please, do not break my production!

I'm somewhat disappointed we are rushing that much. I tend to close such PRs.

Would you elaborate what is going on here?

**Comment by FredyC** [comment]
I am not rushing anything, I should probably put there [WIP] marker. Essentially I just wanted to see if it will work, it was quick change.

I suppose we would need to add manual polyfill there by checking if `Object.assign` exists although that still would mean that polyfilled could would have to be included in the package. That's kinda sad story...

**Comment by koresar** [comment]
Feel free to play with polyfills. Like
```js
Object.assign = Object.assign || require('lodash/assign');
```

**Comment by ericelliott** [comment]
> Feel free to play with polyfills. Like

```js
Object.assign = Object.assign || require('lodash/assign');
```

This only works if the system you build on and the system you run it on are the same. );

**Comment by koresar** [comment]
Dammit! :)

**Comment by FredyC** [comment]
Well I wouldn't certainly grab lodash as polyfill, too broad for our needs.

> This only works if the system you build on and the system you run it on are the same. );

I see a problem for scenario when are you bundling on Node 4+, however I don't think that `require` call can be actually tree-shaken. It will get included in bundle in any case. And if you are just running Node, it will be installed there for you to use. So I think we are good here unless I am missing some scenario.

**Comment by FredyC** [comment]
Ok tests are passing with that polyfill, however instead of lodash I would go with this...

https://github.com/zloirock/core-js/blob/v2.4.0/modules/es6.object.assign.js

That's essentially what Babel is including so with some crossed fingers there wouldn't be multiple implementations in a code for someone bundling with Babel.

**Comment by FredyC** [comment]
@ericelliott Just tried to build stampit with this polyfill included it `compose.js` and disable `transform-runtime`. Yet it was included in bundle. So I convinced that your statement is not true. Even if you bundle on platform that has support, this will be included for cases you run it somewhere it's not available.

**Pull request closed without merging**
