### PR TITLE
fix the lodash import bug #122

### PR DESCRIPTION
**Pull request by lornally**
fix lodash import bug, because lodash not support full es6-module.

### CODE REVIEW

**Comment by koresar** [comment]
Although, it fails tests now. Could you please also upgrade Travis? Need to drop node 4,5,6 support and add 9,10,11. Please

**Comment by lornally** [comment]
sorry, my first, this is a format error. i have fix it.

**Comment by lornally** [comment]
sorry, my mistake, prettier auto format it, but i don/t know, why it format like that. wait a moment. i will fix it.

**Comment by lornally** [comment]
this time it is ok.  before, i ignore our project use airbnb eslint

**Comment by lornally** [comment]
i have update the wravis

**Pull request merged**
